# @@@@@    @@         @@@@@@@   @@     @@
# @        @@         @@        @@@   @@@
# @        @@         @@@@@@@   @  @ @  @
# @        @@         @@        @   @   @
# @        @@         @@        @       @
# @@@@@    @@@@@@@    @@@@@@@   @       @

location:
  warzone1:
    x: 0
    y: 0
    z: 0
  warzone2:
    x: 0
    y: 0
    z: 0
  warzone3:
    x: 0
    y: 0
    z: 0